//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JonathanRuisi.PixelFontDesigner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources\\CharacterSetDatabase.xml")]
        public string Database_Filename {
            get {
                return ((string)(this["Database_Filename"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentProjectFile {
            get {
                return ((string)(this["CurrentProjectFile"]));
            }
            set {
                this["CurrentProjectFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGB [R=211, G=211, B=211]")]
        public string Preferences_Appearance_AccentColor {
            get {
                return ((string)(this["Preferences_Appearance_AccentColor"]));
            }
            set {
                this["Preferences_Appearance_AccentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGBA [R=0, G=0, B=0, A=48]")]
        public string Preferences_Appearance_AscentOverlayColor {
            get {
                return ((string)(this["Preferences_Appearance_AscentOverlayColor"]));
            }
            set {
                this["Preferences_Appearance_AscentOverlayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGB [R=0, G=0, B=255]")]
        public string Preferences_Appearance_BaselineGuideColor {
            get {
                return ((string)(this["Preferences_Appearance_BaselineGuideColor"]));
            }
            set {
                this["Preferences_Appearance_BaselineGuideColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Preferences_Appearance_BaselineGuideThickness {
            get {
                return ((double)(this["Preferences_Appearance_BaselineGuideThickness"]));
            }
            set {
                this["Preferences_Appearance_BaselineGuideThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGB [R=0, G=191, B=255]")]
        public string Preferences_Appearance_BearingGuideColor {
            get {
                return ((string)(this["Preferences_Appearance_BearingGuideColor"]));
            }
            set {
                this["Preferences_Appearance_BearingGuideColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double Preferences_Appearance_BearingGuideThickness {
            get {
                return ((double)(this["Preferences_Appearance_BearingGuideThickness"]));
            }
            set {
                this["Preferences_Appearance_BearingGuideThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGBA [R=0, G=0, B=0, A=48]")]
        public string Preferences_Appearance_BearingOverlayColor {
            get {
                return ((string)(this["Preferences_Appearance_BearingOverlayColor"]));
            }
            set {
                this["Preferences_Appearance_BearingOverlayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Preferences_Appearance_CharacterSetColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Preferences_Appearance_CharacterSetColors"]));
            }
            set {
                this["Preferences_Appearance_CharacterSetColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGBA [R=0, G=0, B=0, A=48]")]
        public string Preferences_Appearance_DescentOverlayColor {
            get {
                return ((string)(this["Preferences_Appearance_DescentOverlayColor"]));
            }
            set {
                this["Preferences_Appearance_DescentOverlayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Preferences_Appearance_ListBox_SmoothScrolling {
            get {
                return ((bool)(this["Preferences_Appearance_ListBox_SmoothScrolling"]));
            }
            set {
                this["Preferences_Appearance_ListBox_SmoothScrolling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGB [R=255, G=20, B=147]")]
        public string Preferences_Appearance_LowercaseGuideColor {
            get {
                return ((string)(this["Preferences_Appearance_LowercaseGuideColor"]));
            }
            set {
                this["Preferences_Appearance_LowercaseGuideColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double Preferences_Appearance_LowercaseGuideThickness {
            get {
                return ((double)(this["Preferences_Appearance_LowercaseGuideThickness"]));
            }
            set {
                this["Preferences_Appearance_LowercaseGuideThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGB [R=32, G=32, B=32]")]
        public string Preferences_Appearance_MidgroundColor {
            get {
                return ((string)(this["Preferences_Appearance_MidgroundColor"]));
            }
            set {
                this["Preferences_Appearance_MidgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGB [R=0, G=0, B=0]")]
        public string Preferences_Appearance_PixelBorderColor {
            get {
                return ((string)(this["Preferences_Appearance_PixelBorderColor"]));
            }
            set {
                this["Preferences_Appearance_PixelBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Preferences_Appearance_PixelBorderThickness {
            get {
                return ((double)(this["Preferences_Appearance_PixelBorderThickness"]));
            }
            set {
                this["Preferences_Appearance_PixelBorderThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGB [R=222, G=222, B=222]")]
        public string Preferences_Appearance_PixelClearColor {
            get {
                return ((string)(this["Preferences_Appearance_PixelClearColor"]));
            }
            set {
                this["Preferences_Appearance_PixelClearColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGB [R=32, G=139, B=238]")]
        public string Preferences_Appearance_PixelMouseOverColor {
            get {
                return ((string)(this["Preferences_Appearance_PixelMouseOverColor"]));
            }
            set {
                this["Preferences_Appearance_PixelMouseOverColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGB [R=48, G=48, B=48]")]
        public string Preferences_Appearance_PixelSetColor {
            get {
                return ((string)(this["Preferences_Appearance_PixelSetColor"]));
            }
            set {
                this["Preferences_Appearance_PixelSetColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGB [R=50, G=205, B=50]")]
        public string Preferences_Appearance_UppercaseGuideColor {
            get {
                return ((string)(this["Preferences_Appearance_UppercaseGuideColor"]));
            }
            set {
                this["Preferences_Appearance_UppercaseGuideColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double Preferences_Appearance_UppercaseGuideThickness {
            get {
                return ((double)(this["Preferences_Appearance_UppercaseGuideThickness"]));
            }
            set {
                this["Preferences_Appearance_UppercaseGuideThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Little")]
        public global::JonathanRuisi.UtilityLibrary.Endianness Preferences_Export_ArrayDeclaration_Endianness {
            get {
                return ((global::JonathanRuisi.UtilityLibrary.Endianness)(this["Preferences_Export_ArrayDeclaration_Endianness"]));
            }
            set {
                this["Preferences_Export_ArrayDeclaration_Endianness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Column")]
        public global::JonathanRuisi.UtilityLibrary.RowOrColumn Preferences_Export_ArrayDeclaration_Interpretation {
            get {
                return ((global::JonathanRuisi.UtilityLibrary.RowOrColumn)(this["Preferences_Export_ArrayDeclaration_Interpretation"]));
            }
            set {
                this["Preferences_Export_ArrayDeclaration_Interpretation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("static const far rom")]
        public string Preferences_Export_ArrayDeclaration_Keywords {
            get {
                return ((string)(this["Preferences_Export_ArrayDeclaration_Keywords"]));
            }
            set {
                this["Preferences_Export_ArrayDeclaration_Keywords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("font%Wx%H")]
        public string Preferences_Export_ArrayDeclaration_Name {
            get {
                return ((string)(this["Preferences_Export_ArrayDeclaration_Name"]));
            }
            set {
                this["Preferences_Export_ArrayDeclaration_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("unsigned char")]
        public string Preferences_Export_ArrayDeclaration_Type {
            get {
                return ((string)(this["Preferences_Export_ArrayDeclaration_Type"]));
            }
            set {
                this["Preferences_Export_ArrayDeclaration_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int Preferences_Export_ArrayDeclaration_TypeSize {
            get {
                return ((int)(this["Preferences_Export_ArrayDeclaration_TypeSize"]));
            }
            set {
                this["Preferences_Export_ArrayDeclaration_TypeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hexadecimal")]
        public global::JonathanRuisi.UtilityLibrary.Radix Preferences_Export_ArrayElement_Radix {
            get {
                return ((global::JonathanRuisi.UtilityLibrary.Radix)(this["Preferences_Export_ArrayElement_Radix"]));
            }
            set {
                this["Preferences_Export_ArrayElement_Radix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Preferences_Export_Miscellaneous_IncludeComments {
            get {
                return ((bool)(this["Preferences_Export_Miscellaneous_IncludeComments"]));
            }
            set {
                this["Preferences_Export_Miscellaneous_IncludeComments"] = value;
            }
        }
    }
}
